name = "Eriks-cool-modpack"
author = "Erik"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7835f09a5f30e4d3f11c0dd6c780c082ff26e9104e5c90690696b83619b249ac"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
