name = "Eriks-cool-modpack"
author = "Erik"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "219920fd4b2f1f6433a7a71da15c6161ba004b5b33691c75806d3f83db3274b9"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
