name = "Eriks-cool-modpack"
author = "Erik"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5687105cabae77935ddc3142b6dde2bf4177fddc9b0fa66554434c1053e2db54"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
