name = "Eriks-cool-modpack"
author = "Erik"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae418e2ef571c3acd9e0eb795465304dacb573a80f921ee38d2f013ddf555908"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
